export const policyPages = {
  about: {
    title: 'About Storewise',
    titleZh: '关于 Storewise',
    sub: 'An independent App Store research site for price checks, subscription decisions, free-trial hygiene, and practical safety guides.',
    subZh: '独立的 App Store 研究站点，覆盖价格核对、订阅决策、试用管理与实用安全指南。',
    highlights: [
      { label: 'Focus', labelZh: '定位', value: 'App Store research', valueZh: 'App Store 研究' },
      { label: 'Approach', labelZh: '方式', value: 'Guides and tools together', valueZh: '指南与工具并用' },
      { label: 'Content', labelZh: '内容', value: 'Tools, checklists, articles, policies', valueZh: '工具、清单、文章、政策页' },
    ],
    sections: [
      { title: 'Who maintains Storewise', titleZh: '谁在维护 Storewise', text: 'Storewise is maintained by an independent developer who also builds small research tools under the public contact handle @Wolffy_chat_bot. The project started because comparing App Store prices, trial terms, and permission risks across languages was messy and easy to rush. It is a small independent project, not a signup-driven platform. Pages are written and revised by a person who actually uses these workflows, then published as clear bilingual documents that readers can inspect and verify.', textZh: 'Storewise 由一位独立开发者维护，对外联系也使用公开的 @Wolffy_chat_bot。做这个站，是因为跨语言比较 App Store 价格、试用条款和权限风险既琐碎又容易冲动。这是一个小型独立项目，不是以收集注册为核心的平台。页面由真实使用这些流程的人撰写与修订，并以清楚的双语文档发布，方便读者查阅与核验。' },
      { title: 'What Storewise is', titleZh: 'Storewise 是什么', text: 'Storewise is an independent research site for App Store purchase decisions. It combines regional price comparison, subscription cost estimation, free-trial reminders, free-app discovery, risk assessment, decision checklists, and long-form safety guides.', textZh: 'Storewise 是面向 App Store 购买决策的独立研究站点，整合地区价格对比、订阅成本估算、试用提醒、限免发现、风险评估、决策清单和长文安全指南。' },
      { title: 'Why it exists', titleZh: '为什么要做这个站', text: 'Buying on the App Store often means jumping between regional prices, subscription fine print, free-trial end dates, privacy labels, and refund rules. Storewise organizes those signals into pages that are easier to scan and verify before you pay, subscribe, switch regions, or grant permissions.', textZh: '在 App Store 购买时，你常常要在地区价格、订阅细则、试用结束日、隐私标签和退款规则之间来回切换。Storewise 把这些信号整理成更容易浏览和核对的页面，帮助你在付款、订阅、切区或授权前先看明白。' },
      { title: 'How it is maintained', titleZh: '网站如何维护', text: 'Storewise is maintained as an independent project with a preference for static pages, client-side tools, and public data references. That keeps pages fast, easier to audit, and less invasive for visitors. The goal is usefulness and clarity rather than account-heavy workflows.', textZh: 'Storewise 作为独立项目维护，优先使用静态页面、浏览器端工具和公开数据来源。这样页面更快、更容易检查，也更少打扰访问者。整体目标是让网站实用、清楚，而不是堆砌复杂账号流程。' },
      { title: 'Editorial principles', titleZh: '内容原则', text: 'Pages are written to be practical, cautious, and verifiable. The site avoids promising guaranteed outcomes, avoids pressure-heavy calls to action, and encourages users to confirm prices, subscriptions, region changes, refunds, and permissions through official sources.', textZh: '内容尽量保持实用、谨慎、可核验。本站不会承诺结果，也不会用夸张方式催促用户操作；涉及价格、订阅、切区、退款和权限时，会尽量提醒你回到官方来源确认。' },
      { title: 'What Storewise is not', titleZh: 'Storewise 不是什么', text: 'Storewise is not an official Apple property, not a payment platform, not an account service, and not a legal or financial advisor. It is a research helper meant to support safer and more informed user choices.', textZh: 'Storewise 不是 Apple 官方产品，不是支付平台，不是账号服务，也不是法律或财务顾问。它更像一个研究辅助站，用来帮助用户做出更稳妥的信息判断。' },
    ],
    checklist: {
      title: 'What you can expect here',
      titleZh: '你能在这里得到什么',
      items: [
        { text: 'Quick access to practical App Store research tools', textZh: '快速访问实用的 App Store 研究工具' },
        { text: 'Bilingual pages for English and Chinese readers', textZh: '同时照顾中英文访问者的双语页面' },
        { text: 'Clearer explanations before account or payment actions', textZh: '在账号与付款操作前提供更清楚的说明' },
        { text: 'Transparent notes about data sources and limitations', textZh: '明确说明数据来源及结果限制' },
      ],
    },
  },
  contact: {
    title: 'Contact Storewise',
    titleZh: '联系 Storewise',
    sub: 'Questions, corrections, privacy requests, bug reports, or advertising inquiries can be sent to the maintainer.',
    subZh: '如需反馈问题、内容更正、隐私请求、Bug 报告或广告合作，可直接联系维护者。',
    highlights: [
      { label: 'Email', labelZh: '邮箱', value: 'contact@souk.eu.org', valueZh: 'contact@souk.eu.org' },
      { label: 'Chat', labelZh: '聊天', value: '@Wolffy_chat_bot', valueZh: '@Wolffy_chat_bot' },
      { label: 'Best for', labelZh: '适合反馈', value: 'Bugs, content fixes, privacy requests', valueZh: 'Bug、内容更正、隐私请求' },
      { label: 'Response style', labelZh: '处理方式', value: 'Context-first review', valueZh: '优先根据上下文判断' },
    ],
    sections: [
      { title: 'How to reach us', titleZh: '如何联系', text: 'Storewise is maintained by an independent developer. The formal email for corrections, privacy requests, and partnership inquiries is contact@souk.eu.org. The fastest chat contact currently listed on the site is the Telegram bot: @Wolffy_chat_bot. When sending a message, include enough context so the issue can be checked without guessing what page, tool, or language state you were using.', textZh: 'Storewise 由独立开发者维护。用于内容更正、隐私请求与合作咨询的正式邮箱是 contact@souk.eu.org。站内最快的聊天联系方式是 Telegram 机器人：@Wolffy_chat_bot。发送消息时，尽量把页面、工具、语言状态和问题背景说明清楚，便于直接定位。' },
      { title: 'Best way to report content issues', titleZh: '内容问题怎么反馈更有效', text: 'For outdated or inaccurate content, include the page URL, the exact text or section involved, the date you observed it, and any useful supporting context. If the issue relates to App Store data, app name, storefront region, and link details are especially helpful.', textZh: '如果是内容过时或不准确，请附上页面地址、涉及的具体文字或段落、你看到问题的日期，以及任何有帮助的背景信息。如果问题与 App Store 数据有关，应用名称、地区商店和链接信息会很有帮助。' },
      { title: 'Best way to report tool bugs', titleZh: '工具 Bug 如何反馈', text: 'For tool issues, the most useful report usually contains reproduction steps, browser and device details, what you expected to happen, and what actually happened. A screenshot is very helpful when the problem involves layout, language switching, mobile display, or a broken result state.', textZh: '如果是工具 Bug，最有效的反馈通常包括复现步骤、浏览器和设备信息、预期行为以及实际结果。涉及布局、语言切换、移动端显示或结果异常时，截图会非常有帮助。' },
      { title: 'Privacy and partnership requests', titleZh: '隐私与合作请求', text: 'For privacy-related questions or advertising and partnership inquiries, describe the page involved and the type of request you are making. Storewise does not require registration, so most preference data lives in the browser rather than in a user account on a server.', textZh: '如果是隐私相关问题，或者广告与合作咨询，请说明涉及页面和请求类型。Storewise 不要求注册账号，所以大多数偏好数据保存在浏览器中，而不是服务器用户账户里。' },
      { title: 'What helps us respond faster', titleZh: '什么信息能加快处理', text: 'Short, specific, evidence-backed messages are easiest to act on. If you already tested on another browser, device, or language setting, say so. That makes it much easier to tell the difference between a page bug, a data-source issue, and a local browser problem.', textZh: '简短、具体、带证据的反馈最容易处理。如果你已经换过浏览器、设备或语言设置测试，也请顺手说明。这能帮助更快区分是页面 Bug、数据源问题，还是本地浏览器状态导致的异常。' },
    ],
    checklist: {
      title: 'Contact checklist',
      titleZh: '反馈前建议附上',
      items: [
        { text: 'Page URL or tool name', textZh: '页面地址或工具名称' },
        { text: 'Observed date and device/browser info', textZh: '发现日期与设备 / 浏览器信息' },
        { text: 'Expected result and actual result', textZh: '预期结果与实际结果' },
        { text: 'Screenshots if the issue is visual', textZh: '如果是视觉问题，附上截图' },
      ],
    },
    links: [
      { href: '/privacy', label: 'Privacy Policy', labelZh: '隐私政策' },
      { href: '/editorial', label: 'Editorial Policy', labelZh: '编辑政策' },
    ],
  },
  privacy: {
    title: 'Privacy Policy',
    titleZh: '隐私政策',
    sub: 'What Storewise stores locally, which third-party requests may occur, and how advertising scripts may be used.',
    subZh: '说明 Storewise 会在本地保存什么、可能请求哪些第三方服务，以及广告脚本可能如何使用。',
    effective: 'Effective date: 2026-07-15',
    effectiveZh: '生效日期：2026-07-15',
    highlights: [
      { label: 'Accounts', labelZh: '账号', value: 'No registration required', valueZh: '无需注册账号' },
      { label: 'Storage', labelZh: '存储', value: 'Mostly browser-local', valueZh: '主要保存在浏览器本地' },
      { label: 'Ads', labelZh: '广告', value: 'May use Google AdSense', valueZh: '可能使用 Google AdSense' },
    ],
    sections: [
      { title: '1. Overview', titleZh: '1. 概览', text: 'Storewise is primarily a client-side website. Most pages load as static HTML, JavaScript, and CSS. The site does not ask users to register, sign in, create profiles, or submit passwords just to browse public content and use basic tools.', textZh: 'Storewise 主要是一个浏览器端网站。大多数页面以静态 HTML、JavaScript 和 CSS 方式加载。用户访问公开内容和基础工具时，不需要注册、登录、创建资料或提交密码。' },
      { title: '2. Local browser data', titleZh: '2. 浏览器本地数据', text: 'Language preference, theme choice, saved test addresses, checklist progress, and temporary interface state may be stored in your browser to improve usability. You can clear this information through your browser settings at any time.', textZh: '语言偏好、主题选择、保存的测试地址、清单进度和临时界面状态可能会保存在你的浏览器中，以提升使用体验。你可以随时通过浏览器设置清除这些内容。' },
      { title: '3. Third-party requests', titleZh: '3. 第三方请求', text: 'Some tools may contact Apple public APIs, public IP metadata services, Apple-hosted media resources, public promotional feeds, or links that you intentionally open. Those external services may receive normal request metadata such as IP address, user agent, referrer, or request timing under their own policies.', textZh: '部分工具可能会请求 Apple 公开 API、公开 IP 信息服务、Apple 托管的媒体资源、公开促销源，或你主动打开的外部链接。这些服务可能会根据其自身政策接收常规请求元数据，例如 IP 地址、浏览器标识、来源页和请求时间。' },
      { title: '4. Advertising, Google AdSense, and third-party cookies', titleZh: '4. 广告、Google AdSense 与第三方 Cookie', text: 'We use third-party advertising companies (such as Google AdSense) to serve ads when you visit our website. These companies may use information about your visits to this and other websites (not including your name, address, email address, or telephone number) to provide advertisements about goods and services of interest to you. Storewise may display ads through Google AdSense or similar partners. Google and its partners may use cookies, advertising IDs, local storage, IP address, user-agent, page URL, and similar browser information to serve, measure, and personalize ads according to Google policies and your browser or account choices. This can include third-party cookies and similar technologies for interest-based advertising where permitted. You can manage ad personalization through Google ad settings (for example, https://adssettings.google.com/), browser cookie controls, and platform-level privacy settings. Storewise aims to place ads near substantial page content and keep them separate from interactive tools, but third-party ad delivery is still governed by the advertising provider. For more detail, review Google advertising policies and the options available in your browser.', textZh: '我们使用第三方广告公司（如 Google AdSense）在您访问我们网站时投放广告，这些公司可能会使用有关您访问本网站和其他网站的信息（不包括您的姓名、地址、电子邮箱或电话号码）来投放您感兴趣的广告。Storewise 可能通过 Google AdSense 或类似合作方展示广告。Google 及其合作伙伴可能根据 Google 政策以及你的浏览器或账号选择，使用 Cookie、广告标识、本地存储、IP 地址、User-Agent、页面 URL 和类似浏览器信息来投放、衡量与个性化广告。在允许的情况下，这可能包括用于兴趣广告的第三方 Cookie 及类似技术。你可以通过 Google 广告设置（例如 https://adssettings.google.com/）、浏览器 Cookie 控制以及系统级隐私设置管理广告个性化。Storewise 会尽量只在有有实质说明的区域展示广告，而不是放在空结果或纯错误页，但第三方广告的具体投放仍由广告服务方决定。更多细节请参阅 Google 广告政策与你浏览器中的可用选项。' },
      { title: '5. Interest-based ads and third-party vendors', titleZh: '5. 兴趣广告与第三方广告商', text: 'Third-party vendors, including Google, use cookies to serve ads based on a user\'s prior visits to this website or other websites. Google\'s use of advertising cookies enables it and its partners to serve ads to users based on their visit to this site and/or other sites on the Internet. Users may opt out of personalized advertising by visiting Google Ads Settings. Alternatively, users can opt out of some third-party vendors\' use of cookies for personalized advertising by visiting www.aboutads.info/choices/.', textZh: '包括 Google 在内的第三方供应商会使用 Cookie，根据用户此前对本网站或其他网站的访问情况投放广告。Google 使用广告 Cookie，可使其自身及其合作伙伴根据用户对本站和/或互联网上其他网站的访问情况投放广告。用户可访问 Google 广告设置退出个性化广告；也可访问 www.aboutads.info/choices/ 退出部分第三方供应商将 Cookie 用于个性化广告。' },
      { title: '6. Cookies and similar technologies', titleZh: '6. Cookie 与类似技术', text: 'The site may use first-party preferences such as language and theme in local storage or cookies. When advertising is enabled, third parties such as Google may set or read cookies and similar technologies to deliver and measure ads. You can clear cookies and site data in your browser, use private browsing, or block third-party cookies where your browser allows it. Blocking cookies may reduce personalization or affect some features, but public articles should remain readable.', textZh: '本站可能使用语言、主题等第一方偏好（本地存储或 Cookie）。启用广告后，Google 等第三方可能设置或读取 Cookie 及类似技术以投放和衡量广告。你可以在浏览器中清除 Cookie 与站点数据、使用隐私浏览，或在浏览器允许时拦截第三方 Cookie。拦截 Cookie 可能降低个性化或影响部分功能，但公开文章仍应保持可阅读。' },
      { title: '7. Data minimization', titleZh: '7. 数据最小化', text: 'The site is designed to collect as little direct user information as possible. Feature requests are typically triggered only when you actively use a tool, and explanatory content is still written to remain useful even when a third-party request fails or is blocked.', textZh: '本站的设计目标是尽量少收集直接用户信息。功能请求通常只会在你主动使用某个工具时触发，即使第三方请求失败或被拦截，页面也尽量保留足够的说明内容。' },
      { title: '8. Your choices', titleZh: '8. 你的选择', text: 'You can block cookies, clear local storage, use private browsing, disable JavaScript, or avoid features that rely on third-party services. Some tools may become less convenient or unavailable in those cases, but public informational pages should still remain readable.', textZh: '你可以禁用 Cookie、清除本地存储、使用隐私浏览、关闭 JavaScript，或者避免使用依赖第三方服务的功能。在这些情况下，部分工具可能会变得不方便甚至不可用，但公开的信息页仍应保持可阅读。' },
      { title: '9. Questions or requests', titleZh: '9. 隐私问题与请求', text: 'If you have a privacy question, correction request, or concern about how a page behaves, contact the maintainer with the page URL, observed behavior, date, and any supporting details. Because the site does not center around user accounts, requests are usually handled by reviewing site behavior rather than editing account records.', textZh: '如果你对隐私有疑问、需要更正内容，或者担心某个页面的行为，请联系维护者并附上页面地址、发现情况、日期和支持信息。由于本站并不围绕用户账户运作，相关请求通常是通过检查页面行为来处理，而不是修改账号记录。' },
    ],
    checklist: {
      title: 'Privacy summary',
      titleZh: '隐私摘要',
      items: [
        { text: 'No required sign-up for normal use', textZh: '正常使用不需要注册' },
        { text: 'Preferences are mainly stored in your browser', textZh: '偏好设置主要保存在浏览器中' },
        { text: 'Some tools may contact third-party public services', textZh: '部分工具会请求第三方公开服务' },
        { text: 'Future ad scripts may follow provider-side policies', textZh: '未来广告脚本会遵循提供方政策' },
      ],
    },
    links: [
      { href: '/contact', label: 'Contact', labelZh: '联系' },
      { href: '/data-sources', label: 'Data Sources', labelZh: '数据来源' },
    ],
  },
  disclaimer: {
    title: 'Disclaimer',
    titleZh: '免责声明',
    sub: 'Important limitations, data-source notes, and user responsibility for Storewise tools and guides.',
    subZh: '说明 Storewise 工具、指南、数据来源和外部链接的使用限制，以及用户在操作前需要自行核验的责任。',
    effective: 'Effective date: 2026-07-15',
    effectiveZh: '生效日期：2026-07-15',
    sections: [
      { title: '1. Independent project', titleZh: '1. 独立项目', text: 'Storewise is not affiliated with, endorsed by, sponsored by, or officially connected to Apple, Google, GitHub, Docker, app developers, payment providers, or any third-party service mentioned on the site.', textZh: 'Storewise 是独立项目，与 Apple、Google、GitHub、Docker、应用开发者、支付服务商或本站提到的任何第三方服务不存在隶属、背书、赞助或官方合作关系。' },
      { title: '2. Informational purpose', titleZh: '2. 仅供信息参考', text: 'Content is provided for general information, research, education, and personal decision support. It is not legal, financial, cybersecurity, tax, refund, or purchase advice.', textZh: '本站内容用于一般信息、研究、教育和个人决策辅助，不构成法律、财务、网络安全、税务、退款或购买建议。重要操作前，请以官方页面和专业意见为准。' },
      { title: '3. Verify before acting', titleZh: '3. 操作前请自行核验', text: 'Prices, subscriptions, app metadata, region availability, IP geolocation, and third-party links can change. Verify critical information through official sources before acting.', textZh: '价格、订阅规则、应用元数据、地区可用性、IP 地理位置和第三方链接都可能变化。购买、订阅、切区、安装应用或授权权限前，请通过官方来源再次确认。' },
      { title: '4. Tool limitations', titleZh: '4. 工具结果的限制', text: 'Search results, generated test data, app risk scores, checklists, and network diagnostics are aids for review, not guarantees. Missing data, cached responses, API changes, regional differences, or browser restrictions may affect results.', textZh: '搜索结果、生成的测试数据、应用风险评分、检查清单和网络诊断都只是辅助判断，并不是保证。数据缺失、缓存、API 变化、地区差异或浏览器限制都可能影响结果。' },
      { title: '5. External services and links', titleZh: '5. 外部服务与链接', text: 'Some pages link to App Store pages, Apple resources, public APIs, GitHub repositories, or third-party websites. Storewise does not control those services and is not responsible for their availability, pricing, content, policies, or security practices.', textZh: '部分页面会链接到 App Store、Apple 资源、公开 API、GitHub 仓库或第三方网站。Storewise 不控制这些服务，也不对其可用性、价格、内容、政策或安全实践负责。' },
      { title: '6. Prohibited use', titleZh: '6. 禁止用途', text: 'Do not use Storewise for fraud, impersonation, unauthorized access, credential sharing, account abuse, platform circumvention, spam, scraping abuse, or misuse of generated data.', textZh: '不得将 Storewise 用于欺诈、冒充身份、未授权访问、凭据共享、账号滥用、规避平台规则、垃圾信息、滥用抓取或滥用生成数据。' },
    ],
  },
  terms: {
    title: 'Terms of Use',
    titleZh: '使用条款',
    sub: 'Rules and limitations for using Storewise tools, guides, generated data, and external links.',
    subZh: '说明使用 Storewise 工具、指南、生成数据和外部链接时的规则与限制。',
    effective: 'Effective date: 2026-07-15',
    effectiveZh: '生效日期：2026-07-15',
    highlights: [
      { label: 'Use case', labelZh: '用途', value: 'Research and practical reference', valueZh: '研究与实用参考' },
      { label: 'Limits', labelZh: '限制', value: 'No abuse, no impersonation', valueZh: '禁止滥用与冒充' },
      { label: 'Responsibility', labelZh: '责任', value: 'Verify official sources yourself', valueZh: '关键操作请自行核验官方来源' },
    ],
    sections: [
      { title: '1. Acceptance of terms', titleZh: '1. 接受条款', text: 'By accessing Storewise, you agree to use the site for lawful, personal, research, educational, and development-support purposes. If you do not agree with these terms, please stop using the site.', textZh: '访问 Storewise 即表示你同意仅将本站用于合法的个人、研究、教育和开发辅助目的。如果你不同意这些条款，请停止使用本站。' },
      { title: '2. Informational tools only', titleZh: '2. 仅作为信息工具', text: 'Results are not guarantees, professional advice, purchase recommendations, or approval from Apple or any third-party service. Prices, app metadata, subscription markers, region availability, and IP data can change without notice.', textZh: '工具结果不构成保证、专业建议、购买推荐，也不代表 Apple 或任何第三方服务的批准。价格、应用元数据、订阅标记、地区可用性和 IP 数据都可能随时变化。' },
      { title: '3. User responsibility', titleZh: '3. 用户责任', text: 'You are responsible for checking official sources before purchasing, subscribing, changing account regions, installing apps, granting permissions, or relying on generated test data. Storewise is a research helper, not a final authority.', textZh: '在购买、订阅、切换账号地区、安装应用、授予权限或使用生成测试数据之前，你有责任查看官方来源。Storewise 是研究辅助工具，不是最终权威。' },
      { title: '4. Prohibited use', titleZh: '4. 禁止用途', text: 'Do not use Storewise for fraud, impersonation, unauthorized access, credential sharing, account abuse, platform circumvention, spam, scraping abuse, or misuse of generated data.', textZh: '不得将 Storewise 用于欺诈、冒充身份、未授权访问、凭据共享、账号滥用、规避平台规则、垃圾信息、滥用抓取或滥用生成数据。' },
      { title: '5. External services and links', titleZh: '5. 外部服务与链接', text: 'Some pages link to App Store pages, Apple resources, public APIs, GitHub repositories, or third-party websites. Storewise does not control those services and is not responsible for their availability, pricing, content, or policies.', textZh: '部分页面会链接到 App Store、Apple 资源、公开 API、GitHub 仓库或第三方网站。Storewise 不控制这些服务，也不对其可用性、价格、内容或政策负责。' },
      { title: '6. Site changes and maintenance', titleZh: '6. 站点变更与维护', text: 'Features, pages, routes, content, and data sources may be changed, removed, or reorganized to improve quality, comply with platform policies, reduce abuse, or keep the site maintainable.', textZh: '为了提升质量、遵守平台政策、减少滥用或保持站点可维护性，本站可能调整、移除或重组功能、页面、路由、内容和数据来源。' },
      { title: '7. Service availability', titleZh: '7. 可用性说明', text: 'Storewise is offered on an as-available basis. Maintenance, third-party API changes, network failures, browser restrictions, or regional issues may affect whether a tool works at a given moment.', textZh: 'Storewise 按“可用即提供”的方式运行。维护、第三方 API 变化、网络故障、浏览器限制或地区问题，都可能影响某个工具在特定时刻是否可用。' },
    ],
    checklist: {
      title: 'Using the site responsibly',
      titleZh: '使用本站时请注意',
      items: [
        { text: 'Double-check official information before acting', textZh: '执行关键操作前再次核对官方信息' },
        { text: 'Do not use generated data in harmful ways', textZh: '不要把生成数据用于有害用途' },
        { text: 'Treat results as reference, not guarantees', textZh: '将结果视为参考，而不是保证' },
        { text: 'Respect platform rules and local laws', textZh: '遵守平台规则和当地法律' },
      ],
    },
    links: [
      { href: '/disclaimer', label: 'Disclaimer', labelZh: '免责声明' },
      { href: '/privacy', label: 'Privacy Policy', labelZh: '隐私政策' },
    ],
  },
  editorial: {
    title: 'Editorial Policy',
    titleZh: '编辑政策',
    sub: 'How Storewise writes, reviews, labels, and corrects content for Apple and App Store research.',
    subZh: '说明 Storewise 如何撰写、审查、标注和更正 Apple 与 App Store 相关研究内容。',
    effective: 'Effective date: 2026-07-15',
    effectiveZh: '生效日期：2026-07-15',
    sections: [
      { title: '1. Purpose', titleZh: '1. 内容目的', text: 'Storewise publishes practical, cautious, and verifiable content for Apple and iOS users researching apps, subscriptions, permissions, privacy, refunds, and region decisions.', textZh: 'Storewise 面向 Apple 与 iOS 用户发布实用、谨慎且可核验的内容，帮助用户研究应用、订阅、权限、隐私、退款和地区相关决策。' },
      { title: '2. Independence', titleZh: '2. 编辑独立性', text: 'Storewise is independent. Advertising, affiliate links, sponsorships, external APIs, and third-party services do not determine editorial conclusions or tool behavior.', textZh: 'Storewise 是独立项目。广告、联盟链接、赞助、外部 API 和第三方服务不会决定本站的编辑结论或工具行为。' },
      { title: '3. Source handling', titleZh: '3. 来源处理', text: 'When content references app prices, App Store metadata, public APIs, platform behavior, or third-party resources, Storewise treats those signals as research inputs rather than final authority.', textZh: '当内容引用应用价格、App Store 元数据、公开 API、平台行为或第三方资源时，Storewise 会把这些信息视为研究输入，而不是最终权威。' },
      { title: '4. Review standards', titleZh: '4. 审查标准', text: 'Pages are written to avoid exaggerated claims, hidden guarantees, or pressure tactics. Guidance should explain limits, encourage official verification, and distinguish facts from practical suggestions.', textZh: '页面写作会避免夸大说法、隐藏式保证或施压式引导。指南应说明限制，提醒用户通过官方来源核验，并区分事实信息与实践建议。' },
      { title: '5. Corrections', titleZh: '5. 内容更正', text: 'Users can report outdated, unclear, inaccurate, or incomplete content with the page URL, observed date, affected text, and supporting details. Corrections may update article text, policy notes, sitemap dates, or related page copy.', textZh: '用户可以反馈过时、不清楚、不准确或不完整的内容。反馈时建议提供页面地址、发现日期、相关文字和支持信息。更正可能涉及文章正文、政策说明、sitemap 日期或相关页面文案。' },
      { title: '6. Update rhythm', titleZh: '6. 更新节奏', text: 'Storewise may update guides, glossary entries, checklists, and policy pages when platform behavior changes, user feedback reveals gaps, or maintenance work improves clarity and safety.', textZh: '当平台行为变化、用户反馈暴露缺口，或维护工作能提升清晰度与安全性时，Storewise 可能更新指南、术语、检查清单和政策页面。' },
    ],
  },
  'data-sources': {
    title: 'Data Sources',
    titleZh: '数据来源',
    sub: 'Where Storewise may obtain app, price, IP, address-format, and safety reference information.',
    subZh: '说明 Storewise 可能从哪里获取应用、价格、IP、地址格式和安全参考信息，以及这些数据的限制。',
    effective: 'Effective date: 2026-07-15',
    effectiveZh: '生效日期：2026-07-15',
    sections: [
      { title: '1. Apple and App Store data', titleZh: '1. Apple 与 App Store 数据', text: 'App names, icons, prices, identifiers, descriptions, ratings, and availability signals may come from Apple public APIs, public App Store pages, or Apple-hosted media URLs.', textZh: '应用名称、图标、价格、标识符、描述、评分和可用性信号可能来自 Apple 公开 API、公开 App Store 页面或 Apple 托管的媒体资源地址。' },
      { title: '2. Price and subscription signals', titleZh: '2. 价格与订阅信号', text: 'Price comparison and in-app purchase pages may use Apple lookup responses, public storefront metadata, visible checkout context, and user-entered search terms. Final pricing can still depend on account region, taxes, trials, offers, and payment method.', textZh: '价格对比和内购查询页面可能使用 Apple lookup 响应、公开商店元数据、可见结算上下文和用户输入的搜索词。最终价格仍可能受账号地区、税费、试用、优惠和付款方式影响。' },
      { title: '3. IP and network data', titleZh: '3. IP 与网络数据', text: 'IP checks may request information from public geolocation or network metadata services. Geolocation is approximate and may reflect an ISP, proxy, data center, or registry location rather than a precise physical location.', textZh: 'IP 检测可能会请求公开地理位置或网络元数据服务。地理位置通常只是近似结果，可能反映的是运营商、代理、数据中心或注册信息位置，而不是真实物理位置。' },
      { title: '4. Generated test data', titleZh: '4. 生成的测试数据', text: 'Address generator data is synthetic and intended for development, testing, UI mockups, and sample datasets only. It should not be used for identity verification, delivery, billing, fraud, or platform bypass attempts.', textZh: '地址生成器数据是合成数据，仅用于开发、测试、界面样稿和示例数据集。不应被用于身份验证、配送、账单、欺诈或绕过平台验证。' },
      { title: '5. Editorial and safety references', titleZh: '5. 编辑与安全参考', text: 'Guides, checklists, glossary entries, and risk explanations are written from public platform behavior, Apple documentation patterns, common App Store user issues, and cautious editorial review.', textZh: '指南、检查清单、术语解释和风险说明基于公开平台行为、Apple 文档模式、常见 App Store 用户问题以及谨慎的编辑整理。' },
      { title: '6. Data freshness and corrections', titleZh: '6. 数据时效与更正', text: 'Public data can be delayed, incomplete, cached, unavailable, or different by region. If a result appears wrong, compare it with the official source and contact Storewise with the page URL, date observed, and supporting details.', textZh: '公开数据可能延迟、不完整、被缓存、暂时不可用，或因地区不同而变化。如果结果看起来不正确，请先与官方来源对比，并在反馈时提供页面地址、发现日期和支持信息。' },
    ],
  },
};
