export const profileConfigs = [
  {
    "id": 1,
    "type": "Shadowrocket",
    "name": "As-Lucky",
    "url": "https://yfamilys.com/config/sr/As-Lucky.conf",
    "displayName": "Shadowrocket · As-Lucky",
    "displayNameEn": "Shadowrocket · As-Lucky",
    "descriptionEn": "Shadowrocket configuration file. Import it as a routing, rewrite, and policy template, then adjust as needed.",
    "size": 6175
  },
  {
    "id": 2,
    "type": "Shadowrocket",
    "name": "LOWERTOP",
    "url": "https://yfamilys.com/config/sr/LOWERTOP.conf",
    "displayName": "Shadowrocket · LOWERTOP",
    "displayNameEn": "Shadowrocket · LOWERTOP",
    "descriptionEn": "Shadowrocket configuration file. Import it as a routing, rewrite, and policy template, then adjust as needed.",
    "size": 17170
  },
  {
    "id": 3,
    "type": "Shadowrocket",
    "name": "墨鱼",
    "url": "https://yfamilys.com/config/sr/ddgksf2013.conf",
    "displayName": "Shadowrocket · 墨鱼",
    "displayNameEn": "Shadowrocket · Moyu",
    "descriptionEn": "Shadowrocket configuration file. Import it as a routing, rewrite, and policy template, then adjust as needed.",
    "size": 5778
  },
  {
    "id": 4,
    "type": "Shadowrocket",
    "name": "chxm1023",
    "url": "https://yfamilys.com/config/sr/chxm1023.conf",
    "displayName": "Shadowrocket · chxm1023",
    "displayNameEn": "Shadowrocket · chxm1023",
    "descriptionEn": "Shadowrocket configuration file. Import it as a routing, rewrite, and policy template, then adjust as needed.",
    "size": 19927
  },
  {
    "id": 5,
    "type": "Shadowrocket",
    "name": "ICNNC",
    "url": "https://yfamilys.com/config/sr/ICNNC.conf",
    "displayName": "Shadowrocket · ICNNC",
    "displayNameEn": "Shadowrocket · ICNNC",
    "descriptionEn": "Shadowrocket configuration file. Import it as a routing, rewrite, and policy template, then adjust as needed.",
    "size": 12760
  },
  {
    "id": 6,
    "type": "Shadowrocket",
    "name": "limbopro",
    "url": "https://yfamilys.com/config/sr/limbopro.conf",
    "displayName": "Shadowrocket · limbopro",
    "displayNameEn": "Shadowrocket · limbopro",
    "descriptionEn": "Shadowrocket configuration file. Import it as a routing, rewrite, and policy template, then adjust as needed.",
    "size": 3826
  },
  {
    "id": 7,
    "type": "Shadowrocket",
    "name": "w37fhy",
    "url": "https://yfamilys.com/config/sr/w37fhy.conf",
    "displayName": "Shadowrocket · w37fhy",
    "displayNameEn": "Shadowrocket · w37fhy",
    "descriptionEn": "Shadowrocket configuration file. Import it as a routing, rewrite, and policy template, then adjust as needed.",
    "size": 3965
  },
  {
    "id": 8,
    "type": "Shadowrocket",
    "name": "yfamily",
    "url": "https://yfamilys.com/config/shadowrocket_basic.conf",
    "displayName": "Shadowrocket · yfamily",
    "displayNameEn": "Shadowrocket · yfamily",
    "descriptionEn": "Shadowrocket configuration file. Import it as a routing, rewrite, and policy template, then adjust as needed.",
    "size": 7749
  },
  {
    "id": 9,
    "type": "Shadowrocket",
    "name": "yfamily轻量版",
    "url": "https://yfamilys.com/config/shadowrocket_lite.conf",
    "displayName": "Shadowrocket · yfamily轻量版",
    "displayNameEn": "Shadowrocket · yfamily Lite",
    "descriptionEn": "Shadowrocket configuration file. Import it as a routing, rewrite, and policy template, then adjust as needed.",
    "size": 3117
  },
  {
    "id": 10,
    "type": "Quantumult X",
    "name": "可莉 最小配置",
    "url": "https://yfamilys.com/config/qx/luestr.conf",
    "displayName": "Quantumult X · 可莉 最小配置",
    "displayNameEn": "Quantumult X · Keli Minimal",
    "descriptionEn": "Quantumult X configuration file. Useful as a rules, rewrite, and policy-group template.",
    "size": 4041
  },
  {
    "id": 11,
    "type": "Quantumult X",
    "name": "可莉 进阶配置",
    "url": "https://yfamilys.com/config/qx/luestr2.conf",
    "displayName": "Quantumult X · 可莉 进阶配置",
    "displayNameEn": "Quantumult X · Keli Advanced",
    "descriptionEn": "Quantumult X configuration file. Useful as a rules, rewrite, and policy-group template.",
    "size": 7992
  },
  {
    "id": 12,
    "type": "Quantumult X",
    "name": "墨鱼",
    "url": "https://yfamilys.com/config/qx/ddgksf2013.conf",
    "displayName": "Quantumult X · 墨鱼",
    "displayNameEn": "Quantumult X · Moyu",
    "descriptionEn": "Quantumult X configuration file. Useful as a rules, rewrite, and policy-group template.",
    "size": 19172
  },
  {
    "id": 13,
    "type": "Quantumult X",
    "name": "Centralmatrix3",
    "url": "https://yfamilys.com/config/qx/Centralmatrix3.conf",
    "displayName": "Quantumult X · Centralmatrix3",
    "displayNameEn": "Quantumult X · Centralmatrix3",
    "descriptionEn": "Quantumult X configuration file. Useful as a rules, rewrite, and policy-group template.",
    "size": 6156
  },
  {
    "id": 14,
    "type": "Quantumult X",
    "name": "As-Lucky",
    "url": "https://yfamilys.com/config/qx/As-Lucky.conf",
    "displayName": "Quantumult X · As-Lucky",
    "displayNameEn": "Quantumult X · As-Lucky",
    "descriptionEn": "Quantumult X configuration file. Useful as a rules, rewrite, and policy-group template.",
    "size": 14325
  },
  {
    "id": 15,
    "type": "Quantumult X",
    "name": "Orz-3",
    "url": "https://yfamilys.com/config/qx/Orz-3.conf",
    "displayName": "Quantumult X · Orz-3",
    "displayNameEn": "Quantumult X · Orz-3",
    "descriptionEn": "Quantumult X configuration file. Useful as a rules, rewrite, and policy-group template.",
    "size": 7295
  },
  {
    "id": 16,
    "type": "Quantumult X",
    "name": "fmz200",
    "url": "https://yfamilys.com/config/qx/fmz200.conf",
    "displayName": "Quantumult X · fmz200",
    "displayNameEn": "Quantumult X · fmz200",
    "descriptionEn": "Quantumult X configuration file. Useful as a rules, rewrite, and policy-group template.",
    "size": 14617
  },
  {
    "id": 17,
    "type": "Quantumult X",
    "name": "w37fhy",
    "url": "https://yfamilys.com/config/qx/w37fhy.conf",
    "displayName": "Quantumult X · w37fhy",
    "displayNameEn": "Quantumult X · w37fhy",
    "descriptionEn": "Quantumult X configuration file. Useful as a rules, rewrite, and policy-group template.",
    "size": 13936
  },
  {
    "id": 18,
    "type": "Quantumult X",
    "name": "Sonmbs",
    "url": "https://yfamilys.com/config/qx/Sonmbs.conf",
    "displayName": "Quantumult X · Sonmbs",
    "displayNameEn": "Quantumult X · Sonmbs",
    "descriptionEn": "Quantumult X configuration file. Useful as a rules, rewrite, and policy-group template.",
    "size": 8953
  },
  {
    "id": 19,
    "type": "Quantumult X",
    "name": "limbopro",
    "url": "https://yfamilys.com/config/qx/limbopro.conf",
    "displayName": "Quantumult X · limbopro",
    "displayNameEn": "Quantumult X · limbopro",
    "descriptionEn": "Quantumult X configuration file. Useful as a rules, rewrite, and policy-group template.",
    "size": 3826
  },
  {
    "id": 20,
    "type": "Quantumult X",
    "name": "GodMoli",
    "url": "https://yfamilys.com/config/qx/GodMoli.conf",
    "displayName": "Quantumult X · GodMoli",
    "displayNameEn": "Quantumult X · GodMoli",
    "descriptionEn": "Quantumult X configuration file. Useful as a rules, rewrite, and policy-group template.",
    "size": 22429
  },
  {
    "id": 21,
    "type": "Quantumult X",
    "name": "erdongchanyo",
    "url": "https://yfamilys.com/config/qx/erdongchanyo.conf",
    "displayName": "Quantumult X · erdongchanyo",
    "displayNameEn": "Quantumult X · erdongchanyo",
    "descriptionEn": "Quantumult X configuration file. Useful as a rules, rewrite, and policy-group template.",
    "size": 9268
  },
  {
    "id": 22,
    "type": "Quantumult X",
    "name": "Tartarus2014",
    "url": "https://yfamilys.com/config/qx/Tartarus2014.conf",
    "displayName": "Quantumult X · Tartarus2014",
    "displayNameEn": "Quantumult X · Tartarus2014",
    "descriptionEn": "Quantumult X configuration file. Useful as a rules, rewrite, and policy-group template.",
    "size": 6312
  },
  {
    "id": 23,
    "type": "Quantumult X",
    "name": "Repcz",
    "url": "https://yfamilys.com/config/qx/Repcz.conf",
    "displayName": "Quantumult X · Repcz",
    "displayNameEn": "Quantumult X · Repcz",
    "descriptionEn": "Quantumult X configuration file. Useful as a rules, rewrite, and policy-group template.",
    "size": 10652
  },
  {
    "id": 24,
    "type": "Quantumult X",
    "name": "89996462",
    "url": "https://yfamilys.com/config/qx/89996462.conf",
    "displayName": "Quantumult X · 89996462",
    "displayNameEn": "Quantumult X · 89996462",
    "descriptionEn": "Quantumult X configuration file. Useful as a rules, rewrite, and policy-group template.",
    "size": 8875
  },
  {
    "id": 25,
    "type": "Quantumult X",
    "name": "KOP-XIAO",
    "url": "https://yfamilys.com/config/qx/KOP-XIAO.conf",
    "displayName": "Quantumult X · KOP-XIAO",
    "displayNameEn": "Quantumult X · KOP-XIAO",
    "descriptionEn": "Quantumult X configuration file. Useful as a rules, rewrite, and policy-group template.",
    "size": 16901
  },
  {
    "id": 26,
    "type": "Quantumult X",
    "name": "GeQ1an",
    "url": "https://yfamilys.com/config/qx/GeQ1an.conf",
    "displayName": "Quantumult X · GeQ1an",
    "displayNameEn": "Quantumult X · GeQ1an",
    "descriptionEn": "Quantumult X configuration file. Useful as a rules, rewrite, and policy-group template.",
    "size": 12495
  },
  {
    "id": 27,
    "type": "Quantumult X",
    "name": "zwf234",
    "url": "https://yfamilys.com/config/qx/zwf234.conf",
    "displayName": "Quantumult X · zwf234",
    "displayNameEn": "Quantumult X · zwf234",
    "descriptionEn": "Quantumult X configuration file. Useful as a rules, rewrite, and policy-group template.",
    "size": 11857
  },
  {
    "id": 28,
    "type": "Quantumult X",
    "name": "yfamily",
    "url": "https://yfamilys.com/config/qx.conf",
    "displayName": "Quantumult X · yfamily",
    "displayNameEn": "Quantumult X · yfamily",
    "descriptionEn": "Quantumult X configuration file. Useful as a rules, rewrite, and policy-group template.",
    "size": 8505
  },
  {
    "id": 29,
    "type": "Quantumult X",
    "name": "yfamily轻量版",
    "url": "https://yfamilys.com/config/qx-lite.conf",
    "displayName": "Quantumult X · yfamily轻量版",
    "displayNameEn": "Quantumult X · yfamily Lite",
    "descriptionEn": "Quantumult X configuration file. Useful as a rules, rewrite, and policy-group template.",
    "size": 3250
  },
  {
    "id": 30,
    "type": "Loon",
    "name": "As-Lucky",
    "url": "https://yfamilys.com/config/lo/As-Lucky.conf",
    "displayName": "Loon · As-Lucky",
    "displayNameEn": "Loon · As-Lucky",
    "descriptionEn": "Loon configuration file. Useful for rules, plugins, scripts, and MITM setup.",
    "size": 8960
  },
  {
    "id": 31,
    "type": "Loon",
    "name": "可莉 最小配置",
    "url": "https://yfamilys.com/config/lo/luestr.conf",
    "displayName": "Loon · 可莉 最小配置",
    "displayNameEn": "Loon · Keli Minimal",
    "descriptionEn": "Loon configuration file. Useful for rules, plugins, scripts, and MITM setup.",
    "size": 5591
  },
  {
    "id": 32,
    "type": "Loon",
    "name": "可莉 进阶配置",
    "url": "https://yfamilys.com/config/lo/luestr2.conf",
    "displayName": "Loon · 可莉 进阶配置",
    "displayNameEn": "Loon · Keli Advanced",
    "descriptionEn": "Loon configuration file. Useful for rules, plugins, scripts, and MITM setup.",
    "size": 7870
  },
  {
    "id": 33,
    "type": "Loon",
    "name": "Tartarus2014",
    "url": "https://yfamilys.com/config/lo/Tartarus2014.conf",
    "displayName": "Loon · Tartarus2014",
    "displayNameEn": "Loon · Tartarus2014",
    "descriptionEn": "Loon configuration file. Useful for rules, plugins, scripts, and MITM setup.",
    "size": 7378
  },
  {
    "id": 34,
    "type": "Loon",
    "name": "erdongchanyo",
    "url": "https://yfamilys.com/config/lo/erdongchanyo.conf",
    "displayName": "Loon · erdongchanyo",
    "displayNameEn": "Loon · erdongchanyo",
    "descriptionEn": "Loon configuration file. Useful for rules, plugins, scripts, and MITM setup.",
    "size": 9433
  },
  {
    "id": 35,
    "type": "Loon",
    "name": "yfamily",
    "url": "https://yfamilys.com/config/loon.conf",
    "displayName": "Loon · yfamily",
    "displayNameEn": "Loon · yfamily",
    "descriptionEn": "Loon configuration file. Useful for rules, plugins, scripts, and MITM setup.",
    "size": 9517
  },
  {
    "id": 36,
    "type": "Loon",
    "name": "yfamily轻量版",
    "url": "https://yfamilys.com/config/loon-lite.conf",
    "displayName": "Loon · yfamily轻量版",
    "displayNameEn": "Loon · yfamily Lite",
    "descriptionEn": "Loon configuration file. Useful for rules, plugins, scripts, and MITM setup.",
    "size": 4193
  },
  {
    "id": 37,
    "type": "Surge",
    "name": "TributePaulWalker",
    "url": "https://yfamilys.com/config/sg/TributePaulWalker.conf",
    "displayName": "Surge · TributePaulWalker",
    "displayNameEn": "Surge · TributePaulWalker",
    "descriptionEn": "Surge configuration file. Useful for managed rules, policy groups, and proxy client setup.",
    "size": 16388
  },
  {
    "id": 38,
    "type": "Surge",
    "name": "erdongchanyo",
    "url": "https://yfamilys.com/config/sg/erdongchanyo.conf",
    "displayName": "Surge · erdongchanyo",
    "displayNameEn": "Surge · erdongchanyo",
    "descriptionEn": "Surge configuration file. Useful for managed rules, policy groups, and proxy client setup.",
    "size": 8396
  },
  {
    "id": 39,
    "type": "Surge",
    "name": "Tartarus2014",
    "url": "https://yfamilys.com/config/sg/Tartarus2014.conf",
    "displayName": "Surge · Tartarus2014",
    "displayNameEn": "Surge · Tartarus2014",
    "descriptionEn": "Surge configuration file. Useful for managed rules, policy groups, and proxy client setup.",
    "size": 8375
  },
  {
    "id": 40,
    "type": "Surge",
    "name": "As-Lucky",
    "url": "https://yfamilys.com/config/sg/As-Lucky.conf",
    "displayName": "Surge · As-Lucky",
    "displayNameEn": "Surge · As-Lucky",
    "descriptionEn": "Surge configuration file. Useful for managed rules, policy groups, and proxy client setup.",
    "size": 6784
  },
  {
    "id": 41,
    "type": "Surge",
    "name": "Zeaphyou",
    "url": "https://yfamilys.com/config/sg/Zeaphyou.conf",
    "displayName": "Surge · Zeaphyou",
    "displayNameEn": "Surge · Zeaphyou",
    "descriptionEn": "Surge configuration file. Useful for managed rules, policy groups, and proxy client setup.",
    "size": 1053
  },
  {
    "id": 42,
    "type": "Surge",
    "name": "深巷有喵",
    "url": "https://yfamilys.com/config/sg/Rabbit-Spec.conf",
    "displayName": "Surge · 深巷有喵",
    "displayNameEn": "Surge · Rabbit Spec",
    "descriptionEn": "Surge configuration file. Useful for managed rules, policy groups, and proxy client setup.",
    "size": 5618
  },
  {
    "id": 43,
    "type": "Surge",
    "name": "yfamily",
    "url": "https://yfamilys.com/config/surge-url-test.conf",
    "displayName": "Surge · yfamily",
    "displayNameEn": "Surge · yfamily",
    "descriptionEn": "Surge configuration file. Useful for managed rules, policy groups, and proxy client setup.",
    "size": 6497
  },
  {
    "id": 44,
    "type": "Surge",
    "name": "yfamily轻量版",
    "url": "https://yfamilys.com/config/surge-url-test-lite.conf",
    "displayName": "Surge · yfamily轻量版",
    "displayNameEn": "Surge · yfamily Lite",
    "descriptionEn": "Surge configuration file. Useful for managed rules, policy groups, and proxy client setup.",
    "size": 2970
  },
  {
    "id": 45,
    "type": "Stash",
    "name": "Coldvvater",
    "url": "https://yfamilys.com/config/st/Coldvvater.yaml",
    "displayName": "Stash · Coldvvater",
    "displayNameEn": "Stash · Coldvvater",
    "descriptionEn": "Stash configuration file. Useful for Clash-compatible rules, policies, and subscription templates.",
    "size": 14093
  },
  {
    "id": 46,
    "type": "Stash",
    "name": "jnlaoshu",
    "url": "https://yfamilys.com/config/st/jnlaoshu.yaml",
    "displayName": "Stash · jnlaoshu",
    "displayNameEn": "Stash · jnlaoshu",
    "descriptionEn": "Stash configuration file. Useful for Clash-compatible rules, policies, and subscription templates.",
    "size": 7201
  },
  {
    "id": 47,
    "type": "Stash",
    "name": "yfamily",
    "url": "https://yfamilys.com/config/stash-auto.yaml",
    "displayName": "Stash · yfamily",
    "displayNameEn": "Stash · yfamily",
    "descriptionEn": "Stash configuration file. Useful for Clash-compatible rules, policies, and subscription templates.",
    "size": 14595
  },
  {
    "id": 48,
    "type": "Stash",
    "name": "yfamily轻量版",
    "url": "https://yfamilys.com/config/stash-auto-lite.yaml",
    "displayName": "Stash · yfamily轻量版",
    "displayNameEn": "Stash · yfamily Lite",
    "descriptionEn": "Stash configuration file. Useful for Clash-compatible rules, policies, and subscription templates.",
    "size": 6338
  }
  ,{
    "id": 49,
    "type": "去广告规则",
    "name": "blackmatrix7 广告分流",
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Advertising/Advertising.list",
    "displayName": "去广告 · blackmatrix7 Advertising",
    "displayNameEn": "Adblock · blackmatrix7 Advertising",
    "category": "adblock",
    "repo": "blackmatrix7/ios_rule_script",
    "stars": 26021,
    "updatedAt": "2026-05-11",
    "description": "高热度 iOS 规则仓库的广告域名分流规则，适合 Surge/Stash/Loon/Shadowrocket 等兼容 list 的客户端按需引用。",
    "descriptionEn": "Popular ad domain rules from blackmatrix7/ios_rule_script for Surge-compatible clients.",
    "size": 0
  },
  {
    "id": 50,
    "type": "去广告规则",
    "name": "ACL4SSR BanAD",
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list",
    "displayName": "去广告 · ACL4SSR BanAD",
    "displayNameEn": "Adblock · ACL4SSR BanAD",
    "category": "adblock",
    "repo": "ACL4SSR/ACL4SSR",
    "stars": 6046,
    "updatedAt": "2026-02-03",
    "description": "ACL4SSR 维护的广告拦截规则片段，适合 Clash/Stash/Mihomo 或可转换规则场景。",
    "descriptionEn": "ACL4SSR ad blocking rule snippet for Clash/Stash/Mihomo-style usage.",
    "size": 0
  },
  {
    "id": 51,
    "type": "去广告规则",
    "name": "fmz200 App 去广告插件合集",
    "url": "https://github.com/fmz200/wool_scripts/tree/main",
    "displayName": "去广告 · fmz200 wool_scripts",
    "displayNameEn": "Adblock · fmz200 wool_scripts",
    "category": "adblock",
    "repo": "fmz200/wool_scripts",
    "stars": 4976,
    "updatedAt": "2026-04-27",
    "description": "收集 Loon、Surge、Quantumult X、Shadowrocket、Egern 的配置与去广告规则，适合按 App 查找插件/重写。",
    "descriptionEn": "App-specific adblock plugins and rewrites for Loon, Surge, Quantumult X, Shadowrocket, and Egern.",
    "size": 0
  },
  {
    "id": 52,
    "type": "复写脚本",
    "name": "blackmatrix7 Rewrite",
    "url": "https://github.com/blackmatrix7/ios_rule_script/tree/master/rewrite",
    "displayName": "复写脚本 · blackmatrix7 Rewrite",
    "displayNameEn": "Rewrite · blackmatrix7 Rewrite",
    "category": "rewrite",
    "repo": "blackmatrix7/ios_rule_script",
    "stars": 26021,
    "updatedAt": "2026-05-11",
    "description": "复写规则入口，覆盖多客户端可用的 rewrite/module/plugin 资源；使用前建议查看对应目录说明。",
    "descriptionEn": "Rewrite resources for multiple clients; check each directory before importing.",
    "size": 0
  },
  {
    "id": 53,
    "type": "复写脚本",
    "name": "blackmatrix7 Gallery",
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/script/gallery.json",
    "displayName": "复写脚本 · Quantumult X Gallery",
    "displayNameEn": "Rewrite · Quantumult X Gallery",
    "category": "rewrite",
    "repo": "blackmatrix7/ios_rule_script",
    "stars": 26021,
    "updatedAt": "2026-05-11",
    "description": "Quantumult X Gallery 脚本订阅入口，适合集中导入 blackmatrix7 维护的脚本资源。",
    "descriptionEn": "Quantumult X Gallery subscription for scripts maintained by blackmatrix7.",
    "size": 0
  },
  {
    "id": 54,
    "type": "网络分流",
    "name": "Loyalsoldier Clash Rules",
    "url": "https://github.com/Loyalsoldier/clash-rules",
    "displayName": "网络分流 · Loyalsoldier Clash Rules",
    "displayNameEn": "Routing · Loyalsoldier Clash Rules",
    "category": "routing",
    "repo": "Loyalsoldier/clash-rules",
    "stars": 26354,
    "updatedAt": "2026-05-11",
    "description": "高星 Clash Premium 规则集，覆盖直连、代理、广告、私有网络、Apple、Google、Telegram 等常见分流。",
    "descriptionEn": "Highly-starred Clash Premium rule sets for common direct/proxy/ad/private routing.",
    "size": 0
  },
  {
    "id": 55,
    "type": "网络分流",
    "name": "xkww3n Rules",
    "url": "https://rules.xkww3n.cyou/",
    "displayName": "网络分流 · xkww3n Rules",
    "displayNameEn": "Routing · xkww3n Rules",
    "category": "routing",
    "repo": "xkww3n/Rules",
    "stars": 166,
    "updatedAt": "2026-05-01",
    "description": "每日自动更新的多客户端规则集，支持 Clash、Loon、Quantumult X、Shadowrocket、Stash、Surge、Egern 等。",
    "descriptionEn": "Daily-updated multi-client rules for Clash, Loon, Quantumult X, Shadowrocket, Stash, Surge, Egern, and more.",
    "size": 0
  },
  {
    "id": 56,
    "type": "网络分流",
    "name": "MetaCubeX Meta Rules Dat",
    "url": "https://github.com/MetaCubeX/meta-rules-dat",
    "displayName": "网络分流 · MetaCubeX meta-rules-dat",
    "displayNameEn": "Routing · MetaCubeX meta-rules-dat",
    "category": "routing",
    "repo": "MetaCubeX/meta-rules-dat",
    "stars": 4306,
    "updatedAt": "2026-05-11",
    "description": "Mihomo/Clash Meta 生态常用 geosite、geoip、ruleset 数据仓库，适合进阶分流配置引用。",
    "descriptionEn": "Common geosite, geoip, and ruleset data for Mihomo/Clash Meta advanced routing.",
    "size": 0
  }

];
